### ISSUE TITLE
Course is too Linux / OSX and pyenv-centric.  Coverage of Windows and conda are missing

### ISSUE THREAD

**Issue by richlysakowski** [talkpython/modern-python-projects-course#28]
Course is outdated and too Linux / OSX-centric and pyenv-centric.  Coverage of conda is missing.  

The course is called "Modern-Python-Projects" but it does not have modern ways of managing Python and Python virtual environments!! 

Please update this course to include conda.

**Comment by dmschauer** [comment]
What would be the modern way of managing Python and Python virtual environments? 
In which other ways is the course outdated? 
I just took this course and would be happy to know even better ways to do things in Python

**Comment by switowski** [comment]
Hi @dmschauer I still use the same setup today. That's why I said in the course that what I will show can work reliably for many years.

Of course, there are many other tools for managing Python and virtual environments - new tools come and go all the time. But whether they are "the best" depends on the user. Each has its own set of pros and cons. If you find a tool you like, just go ahead and use it instead.

**Comment by dmschauer** [comment]
Hi @switowski, that's what I was thinking. The tools mentioned in your course are still the same ones I see being used at work today. That's why I was surprised to read someone thinks "it does not have modern ways of managing Python" . Because in my personal experience that's not the case. Great course btw, I like it a lot
